"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[directory]
truncation_length = 3
truncation_symbol = '…/'

[git_branch]
symbol = ' '
format = 'on [$symbol$branch(:$remote_branch)]($style) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[php]
symbol = ' '
format = 'via [$symbol($version)]($style) '
detect_files = ['composer.json', 'artisan']

[nodejs]
symbol = ' '
format = 'via [$symbol($version)]($style) '

[cmd_duration]
min_time = 2_000
format = 'took [$duration]($style) '

[package]
disabled = true
